name: hardhat-test
on:
  push:
    paths:
      - "**.sol"
      - ".github/workflows/hardhat-test.yml"

env:
  PRIVATEKEY: ${{ secrets.PRIVATEKEY }}
  HARDHAT_NETWORK: ${{ secrets.HARDHAT_NETWORK }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Prepare
      - uses: actions/checkout@v2

      - name: Setup NodeJS 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Show NodeJs version    
        run: |
          node --version

      # Validate environment
      - name: Show NPM version    
        run: |
          npm --version

      - name: Install NPM dependencies
        run: |
          npm ci

      # Build
      - name: Compile
        run: |
          npx hardhat test
